image: docker:latest

services:
  - docker:dind

variables:
  POJECT: osn
  APP_IMAGE: $PROJECT:$CI_BUILD_REF_SLUG
  SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
  PROD_APP: osn_app
  PROD_DB: osn_db
  PROD_REDIS: osn_redis
  CORS_ORIGIN_WHITELIST: $CORS_ORIGIN_WHITELIST

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

after_script:
  - echo "image name is $APP_IMAGE"
  - echo $HOME
  - if [[ $(docker images -f dangling=true -q) ]] ; then
    docker rmi $(docker images -f dangling=true -q)
    ; fi

stages:
  - build
  - prod

build:
  stage: build
  script:
    - echo "image name is $APP_IMAGE"
    - docker build
        --pull
        --tag $APP_IMAGE
        .

prod:
  stage: prod
  only:
    - master
  script:
    - if [[ $(docker ps) == *$PROD_APP* ]] ; then
      docker stop $PROD_APP
      ; fi
    - if [[ $(docker ps -a) == *$PROD_APP* ]] ; then
      docker rm $PROD_APP
      ; fi
    - docker run
        --detach
        --restart always
        -p 127.0.0.1:8001:80
        -v /var/www/prod_$PROJECT/media/:/var/www/app/media/
        -v /var/www/prod_$PROJECT/static/:/var/www/static/
        --link $PROD_DB:db
        --link $PROD_REDIS:redis
        --name $PROD_APP
        --env DJANGO_SETTINGS_MODULE=apps.settings.production
        --env DEBUG=$DEBUG
        --env CORS_ORIGIN_WHITELIST=$CORS_ORIGIN_WHITELIST
        --env ALLOWED_HOSTS=*
        --env SECRET_KEY=$SECRET_KEY
        --env SENTRY_DSN=$SENTRY_DSN
        --env DB_BACKEND=django.db.backends.postgresql_psycopg2
        --env DB_HOST=db
        --env DB_PORT=$DB_PORT
        --env DB_USER=$DB_USER
        --env DB_PASS=$DB_PASS
        --env DB_NAME=$DB_NAME
        $APP_IMAGE

db_up:
  stage: prod
  when: manual
  only:
    - master
  script:
    - docker run
        --detach
        --restart always
        --name $PROD_DB
        --env POSTGRES_USER=$DB_USER
        --env POSTGRES_PASSWORD=$DB_PASS
        --env POSTGRES_DB=$DB_NAME
        postgres:13.1

db_down:
  stage: prod
  when: manual
  only:
    - master
  script:
    - if [[ $(docker ps) == *$PROD_DB* ]] ; then
        docker stop $PROD_DB
      ; fi
    - if [[ $(docker ps -a) == *$PROD_DB* ]] ; then
        docker rm $PROD_DB
      ; fi

redis_up:
  stage: prod
  when: manual
  only:
    - master
  script:
    - docker run
        --detach
        --restart always
        --name $PROD_REDIS
        redis:5.0

redis_down:
  stage: prod
  when: manual
  only:
    - master
  script:
    - if [[ $(docker ps) == *$PROD_REDIS* ]] ; then
        docker stop $PROD_REDIS
      ; fi
    - if [[ $(docker ps -a) == *$PROD_REDIS* ]] ; then
        docker rm $PROD_REDIS
      ; fi
